# Generated by Django 5.0.7 on 2024-08-21 06:34

import accounts.otp_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otptoken_alter_user_email_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp',
            field=models.CharField(default=accounts.otp_utils.generate_otp, max_length=6),
        ),
    ]
