# Generated by Django 5.0.7 on 2024-08-19 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='fallback.png', upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=4096)),
                ('price', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('times_ordered', models.IntegerField(default=0)),
                ('left_in_storage', models.IntegerField(default=1)),
                ('categories', models.ManyToManyField(to='shop.category')),
                ('image', models.ManyToManyField(to='shop.image')),
            ],
        ),
    ]
