# Generated by Django 5.0.7 on 2024-08-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycheck',
            name='payer_id',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
